#!/bin/bash

# split [split] [line] [name1] ...
split()
{
    splitline="$2"
    for (( spliti = 3; spliti <= $#; spliti++ ));
    do
        eval eval \$$spliti=${splitline%%$1*}
        splitline=${splitline#*$1}
    done
}

if [ `id -u` -ne 0 ]; then
    echo "Fatal: You need to be root to execute this."
    exit 1
fi

cd ../helper

read namePref

read count
for (( i = 0; i <= count; i++ ));
do
    eval ns=${namePref}ns$i
    eval ns$i=$ns
done

while read line
do
    if [ "s$line" = "s" ]; 
    then
        break
    fi

    split " " "$line" i j prefix

    eval veth$i$j=${namePref}veth${i}-$j
    eval veth$j$i=${namePref}veth${j}-$i

    eval ./execNS \$ns$i ./delVeth \$veth$i$j
done

for (( i = 0; i <= count; i++ ));
do
    eval ./delNS \$ns$i
done
